### ISSUE TITLE
Standardizing Cronitor Libraries

### ISSUE THREAD

**Issue by cronitorio** [jordan0day/cronitor#1]
Hi @jordan0day 

Cronitor would like to start taking responsibility for fostering the development of open-source client libraries. Our Github account would host the clients and take a more active roll in the development of all clients. We'd like to start with Ruby, Python, Java, PHP, Elixir, Javascript, and Bash - https://cronitor.io/docs/open-source-libraries - as well as open-source our own Go client.

Our goal is to help standardize documentation, nomenclature, feature development, and testing, as well as keeping the APIs current, and, in some cases, adding or consolidating Ping and Monitor APIs.

Ideally, we'd like to transfer ownership of existing libraries for continuity.  We'll clearly note original client authors on the README. And any maintainers who would like to continue contributing to the projects will continue to have maintainer access. Would you be interested in helping us do this for the Elixir Ping API client?

**Comment by jordan0day** [comment]
Sure thing, that'd be fine with me.

**Comment by aflanagan** [comment]
Thanks! I just sent you an invite to our organization. Would you mind sending that transfer one more time?
